---
title: "Red card factor"
author: "Sergey Sambor"
date: "September 9, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r dependencies}
source("../get_epl_data.r")
source("../reshape_data.r")
library(ggplot2)
```

Get data
```{r get data}
setwd("../data")
downloadSeasons(2007:2017,1)
data <- readSeasonsData(2007:2017, 1)
setwd("../reports")

data <- basicClean(data)
```

Reshape data
```{r}
# subset data
cards <- data %>% 
  select (FTR, teamRC, oppRC, teamOddsWinAv, teamOddsOppAv)

# introduce advantage and oddsDiff variables
# oddsDiff - advantage in the odds for the opponent
cards <- cards %>% 
  mutate(oddsDiff = teamOddsOppAv - teamOddsWinAv,
         advantage = ifelse(teamRC > oppRC, FALSE, TRUE)) %>%
  filter(!is.na(oddsDiff))

#expSeq <- c(rev(- (exp(seq(0.55, 3.3, length.out = 6)) - 1)), (exp(seq(0, 3.3, length.out = 7)) - 1))

expSeq <- c(rev(- (exp(seq(0.3, 3.4, length.out = 13)) - 1)), (exp(seq(0, 3.4, length.out = 14)) - 1))



catLabels <- c()
for (i in 1:(length(expSeq)-1)) catLabels[i] <- round(mean(expSeq[i:(i+1)]),1) 

#add categories
cards$oddsDiffCat <- cut(cards$oddsDiff, expSeq, labels = catLabels)
summary(cards$oddsDiffCat)
```

```{r}
#rate without advantage
rateWO <- cards %>%
  filter (advantage == FALSE) %>% 
  group_by(oddsDiffCat) %>% 
  summarise(won = mean(ifelse(FTR == 'W', 1, 0)),
            drawn = mean(ifelse(FTR == 'D', 1, 0)),
            lost = mean(ifelse(FTR == 'L', 1, 0)))
#rate within advantage
rateWI <- cards %>%
  filter (advantage == TRUE) %>% 
  group_by(oddsDiffCat) %>% 
  summarise(won = mean(ifelse(FTR == 'W', 1, 0)),
            drawn = mean(ifelse(FTR == 'D', 1, 0)),
            lost = mean(ifelse(FTR == 'L', 1, 0)))
rate <- full_join(rateWO, rateWI, by = "oddsDiffCat", suffix = c(".no_Adv", ".Adv"))
rate$oddsDiffCat <- as.numeric(as.character(rate$oddsDiffCat)) 
```

```{r fig.height=3, echo=FALSE}
ggplot(aes(oddsDiff), data = cards) +
  geom_density(alpha=0.25) + 
  coord_cartesian(xlim = c(-12, 13))
```

```{r echo=FALSE}
genPlot <- ggplot(data = rate, aes(oddsDiffCat, group = 1)) +
  coord_cartesian(xlim = c(-12, 13))
degree <- 5
curves <- genPlot + 
  stat_smooth(aes(y = won.no_Adv, colour = "won.no_Adv"),  method = lm, formula = y ~ poly(x, degree), se = FALSE) +
  stat_smooth(aes(y = drawn.no_Adv, colour = "drawn.no_Adv"),  method = lm, formula = y ~ poly(x, degree), se = FALSE) +
  stat_smooth(aes(y = won.Adv, colour = "won.Adv"),  method = lm, formula = y ~ poly(x, degree), se = FALSE) +
  stat_smooth(aes(y = drawn.Adv, colour = "drawn.Adv"),  method = lm, formula = y ~ poly(x, degree), se = FALSE) +
  scale_color_manual(values = c(won.no_Adv = "#008B00", drawn.no_Adv = "#00008B", 
                                won.Adv = "#708B00", drawn.Adv = "#70008B")) +
  theme(legend.position = "bottom")

curves

```


